#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
obj-$(CONFIG_RT4831A_I2C) += rt4831a_drv.o
obj-$(CONFIG_SM5109_I2C) += sm5109.o
obj-$(CONFIG_SGM37604A_I2C) += sgm37604a.o
obj-$(CONFIG_SECOND_SGM37604A_I2C) += sgm37604a_second.o
ccflags-$(CONFIG_RT4831A_I2C) += -I$(DEVICE_MODULES_PATH)/drivers/leds/