# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input core drivers.
#

obj-$(CONFIG_HX9023S_SAR)		+= hx9031as.o
obj-$(CONFIG_HX9036_SAR)		+= hx9036.o
obj-$(CONFIG_SENSORS)                   += sensors_class.o
